### ISSUE TITLE
Additional user and auth related endpoints

### ISSUE THREAD

**Issue by EricPuskas** [cyps1000/prime-gaming-api#24]
- [x] A user can change their password #4 
- [ ] A user can reset their password, will receive an email, to access a link on the frontend, this link will contain a special short-lived token that ca be used to reset the password.
- [ ] Account verification via email for users
- [x] An admin can change a user's password
- [ ] An admin can reset a user's password and force an email to be sent.
- [ ] When logging in, a recaptca token must also be sent, to validate against spam (for both admin and user logins) #17 
- [ ] When logging in, allow optional remember me flag to manipulate duration of refresh token #16
